# Site settings
title: Pato en Los Angeles
email: pato@patocarr.com
description: > # this means to ignore newlines until "baseurl:"
    P&aacute;gina personal de Patricio Carr - Pat Carr's Personal HomePage
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://patocarr.com" # the base hostname & protocol for your site
#twitter_username: patocarr
#github_username:  patocarr

# Build settings
markdown: kramdown
encoding: utf-8

sass:
    load_paths:
        - _sass
        - bower_components

